week15/SecondDay/CourseManagement/coursemanagement/coursemanagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from courses import views

urlpatterns = [
    url(r'^solution/', include('solutions.urls')),
    url(r'^task/', include('tasks.urls')),
    url(r'^website/', include('website.urls')),
    url(r'^lecture/', include('lectures.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

week15/SecondDay/CourseManagement/coursemanagement/tasks/urls.py
from django.conf.urls import url

from . import views

app_name = "tasks"
urlpatterns = [
    url(r'^$', views.TaskListView.as_view(), name='index'),
    url(r'^add$', views.TaskCreateView.as_view(), name='add_task'),
    url(r'^(?P<pk>[0-9]+)', views.TaskDetailView.as_view(), name='t_detail'),
    url(r'^edit/(?P<pk>[0-9]+)', views.TaskUpdateView.as_view(),
        name='task_edit'),
    url(r'^course/(?P<pk>[0-9]+)', views.TaskCourseListView.as_view(),
        name='course_tasks'),
]

week15/SecondDay/CourseManagement/coursemanagement/website/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'website'
urlpatterns = [
    # url(r'^course/', include('courses.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^profile/$', views.profile, name='profile'),
]

week15/SecondDay/CourseManagement/coursemanagement/website/models.py
from django.db import models

from courses.models import Course


# Create your models here.
class User(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=120)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    @classmethod
    def login(cls, email, password):
        if User.objects.filter(email=email, password=password).exists():
            return User.objects.filter(email=email, password=password)
        else:
            return None


class Student(User):
    course = models.ManyToManyField(Course)


class Teacher(User):
    course = models.ManyToManyField(Course)

week15/SecondDay/CourseManagement/coursemanagement/website/forms.py
from django import forms
from .models import User


class RegisterForm(forms.Form):
    email = forms.EmailField(label="Enter email")
    password = forms.CharField(label="Enter password",
                               widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=20, label="Enter first name")
    last_name = forms.CharField(max_length=20, label="Enter last name")

    def save(self, commit=True):
        user = User.objects.create(email=self.cleaned_data['email'],
                                   password=self.cleaned_data['password'],
                                   first_name=self.cleaned_data['first_name'],
                                   last_name=self.cleaned_data['last_name'])

        user.save()

        return user


class LoginForm(forms.Form):
    email = forms.EmailField(label="Enter email")
    password = forms.CharField(label="Enter password",
                               widget=forms.PasswordInput)

    def save(self, commit=True):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        return User.login(email, password)

week15/SecondDay/CourseManagement/coursemanagement/website/views.py
from django.shortcuts import render, redirect

from .decorators import anon_required, login_required

from .models import User, Student, Teacher

from .forms import LoginForm

from .forms2 import RegisterForm


# Create your views here.
def index(request):
    return render(request, 'website/index.html', locals())


@anon_required(redirect_url='/website/profile')
def register(request):
    registered = False
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect("/")
        form = RegisterForm(request.POST)
        if form.is_valid():
            if not User.objects.filter(email=form.cleaned_data['email'])\
                                      .exists():
                form.save()
                registered = True
                return redirect('/website/login')
            else:
                error = 'User already exists'

    else:
        form = RegisterForm()

    return render(request, 'website/register.html', locals())


@anon_required(redirect_url='/website/profile')
def login(request):
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect("/")
        form = LoginForm(request.POST)
        if form.is_valid():
            u = form.save()
            if u is not None:
                request.session['email'] = form.cleaned_data['email']
                return redirect("/website/profile/")
            else:
                error = "No such user! Register or try again!"
    else:
        form = LoginForm()

    return render(request, 'website/login.html', locals())


def logout(request):
    try:
        del request.session['email']
    except KeyError:
        print("No session detected.")
    return redirect('/website/login')


@login_required(redirect_url='/website/login')
def profile(request):
    perm = None
    teacher = student = False
    try:
        perm = Teacher.objects.get(email=request.session['email'])
        teacher = True
    except Teacher.DoesNotExist:
        try:
            perm = Student.objects.get(email=request.session['email'])
            student = True
        except Student.DoesNotExist:
            return redirect('/')
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect("/")
        elif request.POST.get('+lecture'):
            return redirect("/lecture/new")
        elif request.POST.get('$lecture'):
            return redirect("/course/{}".format(perm.course.all()[0].name))
        return logout(request)
    error = None
    try:
        greeting = "Hello, " + request.session['email']
    except KeyError:
        error = 'Not logged in.'

    return render(request, 'website/profile.html', locals())

week15/SecondDay/CourseManagement/coursemanagement/website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Home Page {% endblock %}</title>
        {% load staticfiles %}
        <link href="https://fonts.googleapis.com/css?family=Verdana" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>

    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

week15/SecondDay/CourseManagement/coursemanagement/website/templates/website/index.html
WEBSITE SHAT

week15/SecondDay/CourseManagement/coursemanagement/website/templates/website/login.html
<h1> Login </h1>
{% if error %} <p><strong>{{ error }}</strong></p> {% endif %}

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>

<form method='POST' action="{% url 'website:login' %}">
{% csrf_token %}
<label>Enter email</label>
<input type="text" name="email"><br />
<label>Enter password</label>
<input type="text" name="password"><br />
<input type="submit" value="Go!" />
{% if registered %}
<p>Registered.</p>
{% endif %}
</form>

week15/SecondDay/CourseManagement/coursemanagement/website/templates/website/profile.html
{% if error %} <p><strong>{{ error }}</strong></p>{% endif %}

{{ greeting }}

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>

{% if teacher %}
<form method='POST'>
{% csrf_token %}
<input type="submit" value="Add lecture" name="+lecture">
</form>
{% endif %}

<form method='POST'>
{% csrf_token %}
<input type="submit" value="View lectures" name="$lecture">
</form>

<br />
<form method='POST'>
{% csrf_token %}
<input type="submit" value="Logout" name="logout">
</form>

week15/SecondDay/CourseManagement/coursemanagement/website/templates/website/register.html
<h1> Registration </h1>
{% if error %} <p><strong>{{ error }}</strong></p> {% endif %}

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>

<form method='POST' action="{% url 'website:register' %}">
{% csrf_token %}
{% for field in form %}
{{ field.label }}
{{ field }}
<br />
{% endfor %}
<input type="submit" value="Go!" />
{% if registered %}
<p>Registered.</p>
{% endif %}
</form>