week15/SecondDay/CourseManagement/coursemanagement/coursemanagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from courses import views

urlpatterns = [
    url(r'^solution/', include('solutions.urls')),
    url(r'^task/', include('tasks.urls')),
    url(r'^website/', include('website.urls')),
    url(r'^lecture/', include('lectures.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

week15/SecondDay/CourseManagement/coursemanagement/courses/urls.py
from django.conf.urls import url

from . import views


app_name = 'courses'
urlpatterns = [
    url(r'^new/$', views.new, name='new'),
    url(r'^edit/(?P<course_name>[a-zA-Z0-9\-]+)/$',
        views.edit_course, name='edit'),
    url(r'^(?P<course_name>[a-zA-Z0-9\-]+)/$', views.detail_course,
        name='detail'),
]

week15/SecondDay/CourseManagement/coursemanagement/lectures/urls.py
from django.conf.urls import url

from . import views

app_name = "lectures"
urlpatterns = [
    url(r'^edit/(?P<lecture_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^(?P<lecture_id>[0-9]+)/$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
]

week15/SecondDay/CourseManagement/coursemanagement/tasks/urls.py
from django.conf.urls import url

from . import views

app_name = "tasks"
urlpatterns = [
    url(r'^$', views.TaskListView.as_view(), name='index'),
    url(r'^add$', views.TaskCreateView.as_view(), name='add_task'),
    url(r'^(?P<pk>[0-9]+)', views.TaskDetailView.as_view(), name='t_detail'),
    url(r'^edit/(?P<pk>[0-9]+)', views.TaskUpdateView.as_view(),
        name='task_edit'),
    url(r'^course/(?P<pk>[0-9]+)', views.TaskCourseListView.as_view(),
        name='course_tasks'),
]

week15/SecondDay/CourseManagement/coursemanagement/courses/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def calc_approx_duration(self):
        if self.start_date is not None and self.end_date is not None:
            return str(self.end_date - self.start_date).split(',')[0]

    def __str__(self):
        return "{}".format(self.name)

week15/SecondDay/CourseManagement/coursemanagement/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse

from django.http import HttpResponseRedirect

from .models import Course
from lectures.models import Lecture


# Create your views here.
def index(request):
    courses = Course.objects.all()

    if request.method == 'POST':
        if request.POST.get('RegButton'):
            return redirect('website/register')
        else:
            return redirect('website/login')

    return render(request, 'courses/index.html', locals())


def new(request):
    course_created = False
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect('/')

        name = request.POST['name']
        description = request.POST['description']
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']

        Course.objects.create(name=name, description=description,
                              start_date=start_date, end_date=end_date)
        course_created = True

    return render(request, 'courses/new_course.html', locals())


def detail_course(request, course_name):
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect('/')
    course = get_object_or_404(Course, name=course_name)

    lectures = list(course.lecture_set.all())

    return render(request, 'courses/course_detail.html', locals())


def edit_course(request, course_name, *args, **kwargs):
    course = get_object_or_404(Course, name=course_name)
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect('/')

        attrs = [attr for attr in list(course.__dict__.keys())
                 if attr != '_state' and attr != 'id']
        course_edited = False

        for attr in attrs:
            if request.POST.get(attr):
                setattr(course, attr, request.POST[attr])
                course_edited = True
        course.save()
    return render(request, 'courses/edit_course.html', locals())

    # kwargs={'course': course}))

week15/SecondDay/CourseManagement/coursemanagement/courses/templates/courses/course_detail.html
<h1> Lectures for {{ course.name }} </h1>

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>


{% for lecture in lectures  %}
<h3>{{ lecture.name }}</h3>
<p><a href="{% url 'lectures:index' lecture.id %}">Lecture description</a></p>
{% endfor %}

week15/SecondDay/CourseManagement/coursemanagement/courses/templates/courses/edit_course.html
<h1>EDITING {{ course.name }}. Leave field blank if you don't want
to change it.</h1>

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>

<form method='POST' action="{% url 'courses:edit' course.name %}">
{% csrf_token %}
  <label>Enter new course name: </label>
  <input type="text" name="name"/><br />
  <label>Enter new course description: </label>
  <input type="text" name="description"><br />
  <label>Enter new start date</label>
  <input type="date" name="start_date"><br />
  <label>Enter new end date</label>
  <input type="date" name="end_date"><br />
  <input type="submit" value="Go!" />
  {% if course_edited %}
    <p>Course edited.</p>
  {% endif %}
</form>

week15/SecondDay/CourseManagement/coursemanagement/courses/templates/courses/index.html
<!doctype html>

<html>
  <head>
    <style>
      body {background-color: #008080;}
      a {color: #fff;}
      a:hover {color: #000;}
    </style>
  </head>
  <body>
    <h1 align="center">Courses index</h1>
    <div align="center">
      <form method="POST">
      {% csrf_token %}
        <input type="submit" value="Register" name="RegButton" style="display: inline;">
        <input type="submit" value="Login" name="LogButton" style="display: inline;">
      </form>
    </div>
    <table border="2" align="center">
      <thead>
        <tr>
          <th>Course Name</th><th>Description</th><th>Start Date</th>
          <th>End Date</th>
          <th>Approx. Duration</th>
          <th>Tasks</th>
        </tr>
        {% for course in courses %}
        <tr>
          <th><a href="course/{{ course.name }}">{{ course.name }}</a></th>
          <th>{{ course.description }}</th>
          <th>{{ course.start_date }}</th>
          <th>{{ course.end_date }}</th>
          <th>{{ course.calc_approx_duration }}</th>
          <th><a href="task/course/{{ course.pk }}">Tasks</a></th>
        </tr>
        {% endfor %}
      </thead>
    </table>
  </body>
</html>

week15/SecondDay/CourseManagement/coursemanagement/courses/templates/courses/new_course.html
<h1>ADDING NEW COURSES TO THE MANAGEMENT SYSTEM</h1>

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>


<form method='POST' action="{% url 'courses:new' %}">
{% csrf_token %}
  <p>Add a course</p>
  <label>Enter course name: </label>
  <input type="text" name="name"/><br />
  <label>Enter course description: </label>
  <input type="text" name="description"><br />
  <label>Enter start date</label>
  <input type="date" name="start_date"><br />
  <label>Enter end date</label>
  <input type="date" name="end_date"><br />
  <input type="submit" value="Go!" />
  {% if course_created %}
    <p>Course added.</p>
  {% endif %}
</form>