week15/SecondDay/CourseManagement/coursemanagement/coursemanagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from courses import views

urlpatterns = [
    url(r'^solution/', include('solutions.urls')),
    url(r'^task/', include('tasks.urls')),
    url(r'^website/', include('website.urls')),
    url(r'^lecture/', include('lectures.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

week15/SecondDay/CourseManagement/coursemanagement/lectures/urls.py
from django.conf.urls import url

from . import views

app_name = "lectures"
urlpatterns = [
    url(r'^edit/(?P<lecture_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^(?P<lecture_id>[0-9]+)/$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
]

week15/SecondDay/CourseManagement/coursemanagement/tasks/urls.py
from django.conf.urls import url

from . import views

app_name = "tasks"
urlpatterns = [
    url(r'^$', views.TaskListView.as_view(), name='index'),
    url(r'^add$', views.TaskCreateView.as_view(), name='add_task'),
    url(r'^(?P<pk>[0-9]+)', views.TaskDetailView.as_view(), name='t_detail'),
    url(r'^edit/(?P<pk>[0-9]+)', views.TaskUpdateView.as_view(),
        name='task_edit'),
    url(r'^course/(?P<pk>[0-9]+)', views.TaskCourseListView.as_view(),
        name='course_tasks'),
]

week15/SecondDay/CourseManagement/coursemanagement/lectures/models.py
from django.db import models

from courses.models import Course


# Create your models here.
class Lecture(models.Model):
    name = models.CharField(max_length=40)
    week = models.IntegerField()
    course = models.ForeignKey(Course)
    url = models.TextField()

week15/SecondDay/CourseManagement/coursemanagement/lectures/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.http import Http404

from website.decorators import login_required

from courses.models import Course
from .models import Lecture
from website.models import Student, Teacher


# Create your views here.
@login_required(redirect_url='/website/login')
def index(request, lecture_id):
    lecture = get_object_or_404(Lecture, pk=lecture_id)
    perm = None
    teacher = student = False

    if request.session.get('email'):
        try:
            perm = Teacher.objects.get(email=request.session.get('email'))
            teacher = True
        except Teacher.DoesNotExist:
            perm = Student.objects.get(email=request.session.get('email'))
            student = True
    if request.method == 'POST':
        if request.POST.get('~lecture'):
            return redirect('/lecture/edit/{}'.format(lecture.id))

    return render(request, 'lectures/index.html', locals())


def new(request):
    lecture_created = False
    courses = Course.objects.all()
    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect('/')

        name = request.POST.get('name')
        week = request.POST.get('week')
        url = request.POST.get('url')
        course = get_object_or_404(Course, pk=request.POST.get('dropdown'))
        lecture = Lecture.objects.create(name=name, week=week, url=url,
                                         course=course)
        lecture_created = True
    return render(request, 'lectures/new.html', locals())


def edit(request, lecture_id):
    lecture = get_object_or_404(Lecture, pk=lecture_id)
    courses = Course.objects.all()
    lecture_edited = False

    if request.method == 'POST':
        if request.POST.get('home'):
            return redirect('/')

        if request.POST.get('dropdown'):
            course = get_object_or_404(Course, pk=request.POST.get('dropdown'))
            lecture.course = course
            lecture_edited = True
        attrs = [attr for attr in list(lecture.__dict__.keys())
                 if attr != '_state' or attr != 'id']
        for attr in attrs:
            if request.POST.get(attr):
                setattr(lecture, attr, request.POST.get(attr))
                lecture_edited = True

        lecture.save()

    return render(request, 'lectures/edit_lecture.html', locals())

week15/SecondDay/CourseManagement/coursemanagement/lectures/templates/lectures/edit_lecture.html
<h1>EDITING {{ lecture.name }}. Leave field blank if you don't want
to change it.</h1>

<form method='POST'>
  {% csrf_token %}
  <input type="submit" value="Home" name="home">
</form>

<form method='POST' action="{% url 'lectures:edit' lecture.id %}">
{% csrf_token %}
  <label>Enter new lecture name: </label>
  <input type="text" name="name"/><br />
  <label>Enter new lecture week: </label>
  <input type="number" name="week"><br />
  <label>Enter new url</label>
  <input type="text" name="url"><br />
  <label>Enter new course</label>
  <select name='dropdown'>
    <option display:none></option>
  {% for course in courses %}
  <option value={{ course.id }}>{{ course.name }}</option>
  {% endfor %}
  </select><br />
  <input type="submit" value="Go!" />
  {% if lecture_edited %}
    <p>Lecture edited.</p>
  {% endif %}
</form>

week15/SecondDay/CourseManagement/coursemanagement/lectures/templates/lectures/index.html
<h1> Details for lecture {{ lecture.name }} of course {{ lecture.course.name }} </h1>

{% if teacher %}
<form method="POST">
  {% csrf_token %}
  <input type="submit" value="Edit lecture" name="~lecture">
</form>
{% endif %}

<table border=2 align='center'>
  <thead>
    <tr>
      <th>Lecture name</th>
      <th>Lecture week</th>
      <th>Lecture slides url</th>
      <th>Course</th>
    </tr>
    <tr>
      <th>{{ lecture.name }}</th>
      <th>week {{ lecture.week }}</th>
      <th>{{ lecture.url }}</th>
      <th>{{ lecture.course.name }}</th>
    </tr>
  </thead>
</table>

week15/SecondDay/CourseManagement/coursemanagement/lectures/templates/lectures/new.html
ADDING NEW LECTURE

<form method='POST'>
{% csrf_token %}
<input type="submit" value="Home" name="home">
</form>


<form method='POST' action="{% url 'lectures:new' %}">
{% csrf_token %}
  <p>Add a lecture</p>
  <label>Enter lecture name: </label>
  <input type="text" name="name" required><br />
  <label>Enter week: </label>
  <input type="text" name="week" required><br />
  <label>Enter lecture url</label>
  <input type="text" name="url" required><br />
  <label>Enter course</label>
  <select name='dropdown'>
  {% for course in courses %}
  <option value={{ course.id }}>{{ course.name }}</option>
  {% endfor %}
  </select><br />
  <input type="submit" value="Go!" />
  {% if lecture_created %}
    <p>Lecture added.</p>
  {% endif %}
</form>